Django Basic/articles/urls.py
from django.urls import path
from articles import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index),
    path('dinner/', views.dinner, name='dinner'),
    path('review/', views.review, name='review'),
    path('create_review/', views.create_review, name='create_review'), 
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

Django Basic/django_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('foods/', include('foods.urls')),
]

Django Basic/foods/urls.py
from django.urls import path

urlpatterns = [
]

Django Basic/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

Django Basic/foods/models.py
from django.db import models

# Create your models here.

Django Basic/articles/views.py
import random 
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    return render(request, 'index.html')

def dinner(request):
    menus = [{"name":'족발', "price": 30000}, {"name": '햄버거', "price": 5000}, 
            {"name": '치킨', "price": 20000}, {"name":'초밥', "price": 15000}]
    pick = random.choice(menus)
    articles = Article.objects.order_by('-create_at')
    context ={
        'pick':pick,
        'menus':menus,
        'articles':articles,
    }
    return render(request, 'dinner.html', context)

def review(request):
    return render(request, 'review.html')

def create_review(request):
    content = request.POST.get('content')
    title = request.POST.get('title')
    article = Article(title=title, content=content)
    article.save()    
    
    return redirect('articles:detail', article.pk)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article':article,
    }
    return render(request, 'detail.html', context)

def delete(request, pk): 
    article = Article.objects.get(pk=pk)
    
    if request.method == 'POST':
        article.delete()
        
    return redirect('articles:dinner')

def edit(request, pk): 
    article = Article.objects.get(pk=pk)
    context = {
        'article':article,
    }
    return render(request, 'edit.html', context)


def update(request, pk): 
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.cotent = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

Django Basic/foods/views.py
from django.shortcuts import render

# Create your views here.

Django Basic/articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>오늘 뭐먹지?</title>
        <!-- CSS only -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous">
    </head>
    <body class="container">
        {% block content %}{% endblock %}
        <!-- JavaScript Bundle with Popper -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    </body>
</html>

Django Basic/articles/templates/detail.html
{% extends 'base.html' %}

{% block content %}
<h2 class ="text-center">Detail</h2>
<h3>{{ article.pk }} 번째 글</h3>
<hr />
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>
<p>작성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
<form action={% url 'articles:delete' article.pk %} method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">DELETE</button>
</form>
<a href={% url 'articles:edit' article.pk %} class="btn btn-primary">EDIT</a><br>
<a href={% url 'articles:dinner' %}>[back]</a>
<hr />
{% endblock content %}

Django Basic/articles/templates/dinner.html
{% extends 'base.html' %}

{% block content %}
<h1> 저녁은 {{pick.name}} 입니다 </h1>
<h1> 메뉴 리스트 </h1>
<ul>
    {% for menu in menus %}
        <li>{{ menu.name }} {{ menu.price }}</li>
    {% endfor %}
</ul>

{% if pick.price > 20000%}
    <p> 비싸다! </p>
{% elif pick.price > 10000 %}
    <p> 해볼만 하다! </p>
{% else %}
    <p> 맛있겠다</p>
{% endif %}
<h1>리뷰 리스트</h1>
<a href={% url 'articles:review' %}>[리뷰 작성하기]</a>
{% for article in articles %}
<p>글 번호: {{ article.pk }}</p>
<p>글 제목: {{ article.title }}</p>
<p>글 내용: {{ article.content }}</p>
<a href={% url 'articles:detail' article.pk %}>[detail]</a>
<hr>
{% endfor %}
{% endblock content %}

Django Basic/articles/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form class="form-group" action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title"> Title: </label>
    <input class="form-control" type="text" id="content" name="title" value="{{ article.title }}" /><br />
    <label for="title"> Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5" >{{ article.content }}</textarea><br />
    <input type="submit" />
</form>
{% endblock content%}

Django Basic/articles/templates/index.html
화이팅

Django Basic/articles/templates/review.html
{% extends 'base.html' %}
{% block content %}
<form class="form-group" action="{% url 'articles:create_review' %}" method="POST">
    {% csrf_token %}
    <label for="title"> Title: </label>
    <input class="form-control" type="text" id="content" name="title" /><br />
    <label for="title"> Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5"></textarea><br />
    <input type="submit" />
</form>
{% endblock content%}

Django Basic/articles/templates/review_result.html
<h1>보내서 받은 내용은 {{ content }} 야!</h1>